// src/app/page.tsx  (server component)
import ClientHome from './home';

export const metadata = {
  title: 'Home | Yoni Tribber',
  description: 'Generated by create next app',
};

export default function HomePage() {
  return <ClientHome />;
}
